from datetime import datetime

from pydantic import BaseModel, ConfigDict, EmailStr, Field

# Base schema with shared fields for all user-related schemas
class UserBase(BaseModel):
    username: str = Field(min_length=1, max_length=50)
    email: EmailStr = Field(max_length=120)

# Schema for creating a new user - only requires username and email
class UserCreate(UserBase):
    pass

# Schema for user responses - includes fields generated by the database
class UserResponse(UserBase):
    # from_attributes=True allows Pydantic to read SQLAlchemy objects,
    # not only dictionaries
    model_config = ConfigDict(from_attributes=True)

    id: int
    image_file: str | None
    image_path: str

# Schema for partial user updates - all fields are optional
class UserUpdate(BaseModel):
    username: str | None = Field(default=None, min_length=1, max_length=50)
    email: EmailStr| None = Field(default=None, max_length=120)
    image_file: str | None = Field(default=None, min_length=1, max_length=200)

# Base schema with shared fields for all post-related schemas
class PostBase(BaseModel):
    title: str = Field(min_length=1, max_length=100)
    content: str = Field(min_length=1)

#  Schema for partial post updates - all fields are optional
class PostUpdate(BaseModel):
    title: str | None = Field(default=None, min_length=1, max_length=100)
    content: str | None = Field(default=None, min_length=1)

# Schema for creating a new post - includes user_id to link post to its owner
class PostCreate(PostBase):
    user_id: int 

# Schema for post responses - includes fields generated by the database
class PostResponse(PostBase):
    model_config = ConfigDict(from_attributes=True)

    id: int
    user_id: int
    date_posted: datetime
    author: UserResponse